build_image:
  image: registry.gitlab.com/citygro/docker-and-compose
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker-compose build
    - docker-compose push
  only:
    - master
    - rafg
    - tags
