name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/oceanum
    permissions:
      id-token: write
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . 'veriframe[dev]'
      -
        name: Test package
        run: pytest -s -v tests
      -
        name: Build package
        run: |
          pip install build
          python -m build -s
      -
        name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
